version: "3.5"

services:
    rabbitmq:
        image: rabbitmq:3.8.5-management-alpine
        hostname: rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
    # message_publisher:
    #     build: ./
    #     stdin_open: true
    #     tty: true


